name: flutter_vap_plugin_example
description: "Demonstrates how to use the flutter_vap_plugin plugin."
publish_to: 'none'
version: 1.0.0
environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_vap_plugin:
    path: ../
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
