name: flutter_vap_plugin
description: "A Flutter plugin for playing Tencent VAP animation videos on Android and iOS, supporting local, asset, and network sources with playback callbacks and loop control."
version: 0.0.9
repository: https://github.com/Matkurban/flutter_vap_plugin.git
homepage: https://github.com/Matkurban/flutter_vap_plugin.git

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurban.flutter_vap_plugin
        pluginClass: FlutterVapPlugin
      ios:
        pluginClass: FlutterVapPlugin

