name: flutter_vap_plugin
description: "Flutter plugin for Vap service"
version: 0.0.1
repository: https://github.com/Matkurban/flutter_vap_plugin.git
homepage: https://github.com/Matkurban/flutter_vap_plugin.git

environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.kurban.flutter_vap_plugin
        pluginClass: FlutterVapPlugin
      ios:
        pluginClass: FlutterVapPlugin

